# Generated by Django 5.0.3 on 2024-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_internship_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
